apiVersion: skaffold/v2beta27
kind: Config

metadata:
  name: hello-app

build:
  artifacts:
  - image: hello-app
    docker:
      dockerfile: Dockerfile

deploy:
  kustomize:
    paths:
    - kustomize/base

profiles:
  - name: v1
    deploy:
      kustomize:
        paths: 
          - kustomize/overlays/v1
  - name: v2
    deploy:
      kustomize:
        paths: 
          - kustomize/overlays/v2