apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  template:
    spec:
      containers:
      - name: python
        image: hello-app
        env:
        - name: GREETING
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.annotations['v']
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
          limits:
            cpu: 50m
            memory: 100Mi
        readinessProbe:
          httpGet:
            port: 8080
            path: /health
        ports:
        - containerPort: 8080
          name: http
